Todo list: Interactive list
alvarorf/todolistjs pull request #3
Opened 2022-05-05 21:03 UTC by alvarorf

In this pull request, the following features are added:
- A new Javascript file ('status.js') contains the functionality about the status's updates, via the 'toggle()' function.
- The checkbox for each task has an event listener.
- A function has been implemented for the button 'Clear all completed' ('clearCompleted()').
- The updated array of items is stored in local storage, so the user gets the correct list values after the page reloads.

Thank you for your comments.

2022-05-05 21:34 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @alvarorf,

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/167029226-aeaa6785-a74e-4cfb-ab58-cc49e670ee11.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct Gitflow setup
✅ No linter error
✅ README is professional
✅ Good descriptive PR


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-05 21:34 UTC, AmaduKamara commented on src/crud.js
>      const todos = Crud.retrieveTodos();
Currently, all the functionalities are working in your app but there are a few changes you need to fix.

- [ ] The add todo is working fine but when I try to enter multiple words in the input field by clicking the space bar key on the keyboard, the todo gets submitted instantly without allowing me to enter other words. I believe a todo is not just one word and it must only get submitted when I click the enter key on the keyboard or a submit button(in this case there is no submit button for this design. That's ok, no worries.). 
- [ ] Kindly make it possible for a user to enter multiply words for todo and only the enter key on the keyboard gets the multiple texts submitted 👍 
- [ ] Also, please do the same fix for updating the todo, I noticed the same problem when I try to update a todo, it does not allow me to enter multiple words. Please fix these issues and your project will be great. 👍

2022-05-05 22:22 UTC, ShahierNashaat requested changes
Hi @alvarorf , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 22:22 UTC, ShahierNashaat commented on src/crud.js
>      element.style.display = 'none';
- [ ] Kindly be noticed that when I try to edit a task the task doesn't update with the new value please fix that.
- [ ] Also when I enter a task with spaces and try to edit it the other words don't show like in the picture.
![Screenshot from 2022-05-06 00-17-43](https://user-images.githubusercontent.com/33752735/167034822-f6511432-eaea-436e-9c86-d5df7d25099f.png)
![Screenshot from 2022-05-06 00-18-01](https://user-images.githubusercontent.com/33752735/167034837-cff4c576-6ed9-4705-b8d7-b81210ea900f.png)

2022-05-06 17:08 UTC, alvarorf commented on src/crud.js
>      element.style.display = 'none';
Thank you for pointing out this issue. Now, when the user tries to edit a task, he/she should press enter to confirm the edit (if he/she focuses out, it is expected that he/she cancelled the edit and the changes won't be applied. This is the expected behavior). It has now been solved. Thanks again.

2022-05-06 17:22 UTC, brytebee approved these changes
Hi, @alvarorf👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-09 03:53 UTC, merged